project_id = "mlbb-pro-topup"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.create-stripe-session]
verify_jwt = true

[functions.wallet-pay]
verify_jwt = true

[functions.admin-update-order]
verify_jwt = true

[functions.exchange-rate-sync]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
